#!/bin/bash

# omarell-theme-set: Set a theme, specified by its name.
# Usage: omarell-theme-set <theme-name>

set_theme() {
  if [[ -z "$1" ]]; then
    echo "Usage: omarell theme set <theme-name>" >&2
    exit 1
  fi


  THEMES_DIR="$HOME/.config/omarell/themes/"
  CURRENT_THEME_DIR="$HOME/.config/omarell/current/theme"

  THEME_NAME="$1"
  THEME_PATH="$THEMES_DIR/$THEME_NAME"

  # Check if the theme entered exists
  if [[ ! -d "$THEME_PATH" ]]; then
    echo "Theme '$THEME_NAME' does not exist in $THEMES_DIR" >&2
    exit 2
  fi

  # Update theme symlinks
  ln -nsf "$THEME_PATH" "$CURRENT_THEME_DIR"

  # Set desktop theme
  if [[ "$XDG_CURRENT_DESKTOP" == *"GNOME"* ]]; then
    # Apply GNOME themes
    source $HOME/.local/share/omarell/themes/$THEME_NAME/gnome.sh

    # Touch alacritty config to pickup the changed theme
    touch "$HOME/.config/alacritty/alacritty.toml"

    # Restart components to apply new theme
    gext disable forge@jmmaranan.com > /dev/null 2>&1
    gext enable forge@jmmaranan.com > /dev/null 2>&1

    # Set new background
    "$HOME/.local/share/omarell/scripts/omarell-theme-bg-next"
  fi

  # Trigger btop config reload
  pkill -SIGUSR2 btop
}

export -f set_theme

# Check if script is being called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  set_theme "$1"
else
  gum spin --title "Setting theme '$1'..." -- bash -c "set_theme \"$1\""
fi